version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgress_password
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: 'Dockerfile'
      context: './nginx'
    ports:
      - '8080:80'
  api:
    build:
      dockerfile: 'Dockerfile'
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgress_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: 'Dockerfile'
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app